# Site settings
title: “Mina Basilious Hanna Arsanious”
description: “Pure Mathematics • Cairo University”
url: "https://minabasilious.github.io" # your GitHub Pages URL
baseurl: ""                            # set to "/" or "" if serving from root

# Theme
remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll

# Author
author:
  name: “Mina Basilious Hanna Arsanious”
  email: basiliousmina2@gmail.com

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
nav:
  - title: Home
    url: /
  - title: Current Work
    url: /current-work/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author: “Mina Basilious Hanna Arsanious”
      comments: false

# Collections (for organizing any future math notes/projects)
collections:
  current-work:
    output: true
    permalink: /:collection/:path/

# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
