# ─────────────────────────────────────────────────────────────────────────────
# Site settings
# ─────────────────────────────────────────────────────────────────────────────
title: "Mina Basilious Hanna Arsanious"
email: "basiliousmina2@gmail.com"
description: "Pure Mathematics portfolio & ongoing research"
baseurl: ""            # the subpath of your site, e.g. /Minas-Math-Page
url: "https://minabasilious.github.io"  # your GitHub Pages domain

# ─────────────────────────────────────────────────────────────────────────────
# Use Minimal Mistakes via remote_theme
# ─────────────────────────────────────────────────────────────────────────────
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme   # to fetch the remote theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# ─────────────────────────────────────────────────────────────────────────────
# Markdown & MathJax support
# ─────────────────────────────────────────────────────────────────────────────
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

# ─────────────────────────────────────────────────────────────────────────────
# Navigation (header links)
# ─────────────────────────────────────────────────────────────────────────────
header_pages:
  - index.md
  - about.md

# ─────────────────────────────────────────────────────────────────────────────
# Footer links & social
# ─────────────────────────────────────────────────────────────────────────────
footer:
  links:
    - title: "Connect"
      items:
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/mina-basilious/"
        - name: "Math Art Gallery"
          url: "https://minabasilious.github.io/Minas-Math-Art-Gallery/"
        - name: "YouTube"
          url: "https://www.youtube.com/@minabasil"
  copyright:
    since: 2025
    author: "Mina Basilious Hanna Arsanious"

# ─────────────────────────────────────────────────────────────────────────────
# Archives configuration (for categories & tags)
# ─────────────────────────────────────────────────────────────────────────────
jekyll_archives:
  enabled:
    - categories
    - tags
  layout:   archive
  permalinks:
    category: /category/:name/
    tag:      /tag/:name/

# ─────────────────────────────────────────────────────────────────────────────
# Pagination
# ─────────────────────────────────────────────────────────────────────────────
paginate: 5
paginate_path: "/page:num/"

# Uncomment if you use Google Analytics
# google_analytics: "UA-XXXXXX-1"
